query getItemsPageWithParams($boardId: ID!, $cursor: String) {
  boards(ids: [$boardId]) {
    items_page(cursor: $cursor) {
      cursor
      items {
        id
        name
        group {
          title
        }
        columns: column_values {
          id
          type
          text
          column {title}
          ... on MirrorValue {display_value}
          ... on FormulaValue {display_value}
          ... on DependencyValue {display_value}
          ... on BoardRelationValue {display_value}
        }
        subitems {
          id
          name
          columns: column_values {
            id
            type
            text
            column {title}
            ... on MirrorValue {display_value}
            ... on FormulaValue {display_value}
            ... on DependencyValue {display_value}
            ... on BoardRelationValue {display_value}
          }
        }
      }
    }
  }
}