query getBoardMetadata($boardId: ID!) {
  boards(ids: [$boardId]) {
    main_columns: columns {
      id
      title
      type
    }
    sub_columns: columns {
      id
      title
      type
    }
  }
}